name: Test "approved" label
on: push

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add "approved" label
      uses: ./
      with:
        MIN_APPROVALS: 1
        LABEL: 'approved'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
